<?php
declare(strict_types=1);

namespace Tychovbh\Mvc\Repositories;

use Exception;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Hash;
use Tychovbh\Mvc\Models\User;
use Tychovbh\Mvc\Models\Wildcard;

class WildcardRepository extends AbstractRepository implements Repository
{
   public function save(array $data)
   {
       $save = parent::save($data); // TODO: Change the autogenerated stub
       return $save;
   }
}
