<?php

namespace Tychovbh\Tests\Mvc\feature\services\HtmlConverter;

use Illuminate\Support\Facades\Config;
use Tychovbh\Mvc\MvcServiceProvider;
use Tychovbh\Mvc\Services\HtmlConverter\LaravelDompdfConverter;
use Orchestra\Testbench\TestCase;

class LaravelDompdfConverterTest extends TestCase
{
    protected function setUp(): void
    {
        putenv('HTML_CONVERTER_SERVICE=true');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [MvcServiceProvider::class];
    }

    /**
     * @test
     */
    public function itCanAddPage()
    {
        $htmlConverter = new LaravelDompdfConverter();
        $html = '<html lang="en"><h1>test</h1></html>';
        $response = $htmlConverter->page($html);
        $this->assertTrue($response->pages[0] === $html);
    }

    /**
     * @test
     */
    public function itCanSave()
    {
        $htmlConverter = new LaravelDompdfConverter();
        $htmlConverter->page('<html lang="nl"><h1>pdf</h1></html>')
            ->save('documents/file.pdf');
        $this->assertFileExists(storage_path('documents/file.pdf'));
    }
}
